### ISSUE TITLE
Related Objects -- Hide Empty Relations doesn't work

### ISSUE THREAD

**Issue by grahamsinger** [tsgrp/hpi#1009]
Config:
![hideemptyrelationsconfig](https://cloud.githubusercontent.com/assets/8784597/13058883/dd7bcb7a-d3eb-11e5-8823-138bcdfd7123.PNG)

Stage:
![hideemptyrelationsstage](https://cloud.githubusercontent.com/assets/8784597/13058885/e249703a-d3eb-11e5-9d58-98f1f95afbb5.PNG)

The config is not working.

**Comment by grahamsinger** [comment]
Fixed this with revision 14248.

CR: Brad W

**Comment by gsteimer** [comment]
Something happened here that broke the Wizard trac on edge and release.  The Wizard trac has two Related Objects sections, both set to display even if there's no related objects:

![image](https://cloud.githubusercontent.com/assets/1377228/13151977/4782d9f8-d632-11e5-91de-3c2d68a6f540.png)

However, when navigating to the stage for a form that does not have any relationships, neither section shows properly:

![image](https://cloud.githubusercontent.com/assets/1377228/13151997/665f6530-d632-11e5-869a-c973dd9dd354.png)

It should show two related objects sections (Workflow Documents and Supporting Documents)

**Comment by grahamsinger** [comment]
Actually fixed with HPI rev14362

**Comment by gsteimer** [comment]
@grahamsinger - this still isn't working right on edge2:

![image](https://cloud.githubusercontent.com/assets/1377228/13190603/b54245e0-d723-11e5-9c72-14ac6338a6b3.png)

Any ideas?

**Comment by grahamsinger** [comment]
Fixed with HPI revision 14372.
