### ISSUE TITLE
Send email from HPI creates subfolder with object name 'null'

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1032]
In the send email action config there are a couple of settings that control where the email object ends up.  Below are the settings from edge2 and release2:

**Determines where the email object should live**
![image](https://cloud.githubusercontent.com/assets/1377228/13498900/77ed9c8c-e121-11e5-8d42-c37958d1029d.png)

If the box above is blank, the application _shuold_ simply put the email in the same folder where the action is being executed from.  If the box is populated, then find or create a subfolder with the given name. Ex: 'Correspondence' as a subfolder.

**Determines what folder tags (if any) should be applied to the email object**
![image](https://cloud.githubusercontent.com/assets/1377228/13498936/b37043cc-e121-11e5-9c7d-08b862b29204.png)

Generally, if folder tags is set, the storage location should be blank, since you want the folder tags to categorize documents in the HPI Stage.  However, if you're not using folder tags, then setting the storage location subfolder makes sense.  Essentially, only one of the above two settings should ever be set to anything (one will always be null).  

However, it looks like something is going wrong with the blank storage location above.  Here's what the actual folder in Alfresco looks like before and after the email is sent:

**Before Email Sent from HPI**
![image](https://cloud.githubusercontent.com/assets/1377228/13499012/0788ddc0-e122-11e5-8586-8c407c3296c4.png)

**After Email Sent from HPI - notice folder called 'null'**
![image](https://cloud.githubusercontent.com/assets/1377228/13499078/566d1366-e122-11e5-86c3-a765dfa387be.png)

Something must be going wrong with the code and it's trying to always create a subfolder no matter what is in the Storage Location config.

Note - the same thing is happening on Documentum:

![image](https://cloud.githubusercontent.com/assets/1377228/13499194/e33f3daa-e122-11e5-8744-90b0b931617b.png)

**Comment by RudraVishweshwar** [comment]
Fixed with revision no. 13989. in Open Content. Instead of null we now have a default .folder-notes folder.

CR-George S

**Comment by gsteimer** [comment]
For posterity - this issue was happening because edge and release are setup to add a folder note when an email is sent.  it was the folder note action that was the problem, not send email...

**Comment by gsteimer** [comment]
Seems like this issue is back.  I just sent a few emails in the insurance trac, and the folder notes are being put in a `null` folder rather than `.foldernotes`:

![image](https://cloud.githubusercontent.com/assets/1377228/24312856/8194a34a-10a8-11e7-90f8-34a5c92edd7d.png)

![image](https://cloud.githubusercontent.com/assets/1377228/24312867/89ca8d36-10a8-11e7-9121-d1b1f7cd368e.png)

There are folder notes in the `.folder-notes` folder as well, so this may only be for Folder Notes created by the Send Email action

**Comment by nquillin91** [comment]
@gsteimer 

Seeing this locally too - is this an issue with spring injection failing when we are calling one action from another action? 

I believe the name for the folder notes container for is defaulted to ".folder-notes" but instead the bean not the java class. If it doesn't get injected - I can see why it would be saving the notes into a folder with the name "null"

**Comment by gsteimer** [comment]
Could be - I seem to remember the fixes above having something to do with chained actions...  Perhaps @RudraVishweshwar remembers?

**Comment by nquillin91** [comment]
Fixed with OC rev #16627
