### ISSUE TITLE
Enhance Get Document Link Action - Make Configurable

### ISSUE THREAD

**Issue by ladams13** [tsgrp/HPI#1054]
To make this action id agnostic and configurable, update this action to be able to configure what properties are queried against when building up a document link.

This can be enabled/disabled in the configuration (if disabled, the chronicle id is generated in the link).

An admin can configure properties and either have it pull off the document (tokenizing the value, ie: $objectName$) or specifying a value (ie: Effective for status).  These configurations will be built as parameters in the document link generated for the user on the front end.

![image](https://cloud.githubusercontent.com/assets/5861266/14149562/5f4694aa-f66a-11e5-94a4-b7efe82f78fa.png)

Original Enhancement for Action: https://github.com/tsgrp/hpi/issues/977

**Comment by ladams13** [comment]
@renesaladrigas closed this today with HPI revision 14644

**Comment by gsteimer** [comment]
@ladams13 @renesaladrigas - this is not working on edge2.  See below:

For TSG-123, which has a 1.3, Draft, the link generated is:

http://edge2.tsgrp.com/hpi//viewOnlyQuery/paramName=Controlled+Document&paramValue=Controlled+Document&paramType=type/paramName=objectName&paramValue=TSG-123-1.3&paramType=property&operator=OPERATOR_EQUALS/paramName=aw_status&paramValue=Effective&paramType=property&operator=OPERATOR_EQUALS

If you try to login with this URL, the following error occurs:

![image](https://cloud.githubusercontent.com/assets/1377228/14190965/f49b6c56-f75a-11e5-9337-815b0cae7464.png)

![image](https://cloud.githubusercontent.com/assets/1377228/14190985/00feb8ea-f75b-11e5-856e-bc0dd02db96a.png)

Trying this on edge1, I get the exact same error.  Here's the link I generated.

http://edge1.tsgrp.com/hpi//viewOnlyQuery/paramName=Controlled+Document&paramValue=Controlled+Document&paramType=type/paramName=objectName&paramValue=TSG-101&paramType=property&operator=OPERATOR_EQUALS/paramName=aw_status&paramValue=Effective&paramType=property&operator=OPERATOR_EQUALS

Also - question - I don't think this is affecting the issue, but can we remove the double `//` in the URL?

**Comment by renesaladrigas** [comment]
@gsteimer That issue was resolved this morning. @m-brouillette pointed out to me that the variable  OcQuery had a capitalization issue. HPI commit 14668 resolves that issue.
As far as double slashes go, commit 14676 takes care of checking the value of app.root before constructing the URL.

**Comment by gsteimer** [comment]
After trying this on edge1 and 2, edge 1 seems to work, but it's still failing on Edge2 (Alfresco).  After logging in, I see this:

![image](https://cloud.githubusercontent.com/assets/1377228/14219601/d1339ee8-f820-11e5-8a31-f930186cee8f.png)

There's an error in OC:

```
15:41:03,912 ERROR [com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl] [ajp-apr-8009-exec-1] Unhandled Exception: 03010510 Invalid node ref - does not contain forward slash: undefined
org.alfresco.service.cmr.repository.MalformedNodeRefException: 03010510 Invalid node ref - does not contain forward slash: undefined
	at org.alfresco.service.cmr.repository.NodeRef.<init>(NodeRef.java:106)
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.enhancedGetProperties(AlfrescoEmbContentImpl.java:521)
...

```

Seems like something is messing up the object ID.  Perhaps it needs to be URL encoded to handle the slashes in Alfresco Object IDs?

**Comment by renesaladrigas** [comment]
GET DOCUMENT LINK -- Fixing Alfresco specific issue, where objectID only link was misshapen and failing in Alfresco environments.

Revision - 14714

CR - Bradley White

**Comment by gsteimer** [comment]
@renesaladrigas @ladams13 - it looks like the problem with the `OcQuery` is back.  On both edge1 and edge2 I see:

![image](https://cloud.githubusercontent.com/assets/1377228/14330396/0dc76b80-fc06-11e5-84b2-bb78ad7b6262.png)

![image](https://cloud.githubusercontent.com/assets/1377228/14330410/1c347834-fc06-11e5-807f-744d4078fd51.png)

**Comment by ladams13** [comment]
looks like @mikeblum's last commit to router.js overrode the fix Rene implemented last week.  @renesaladrigas is updating now

**Comment by renesaladrigas** [comment]
Fixed with revision 14736 by @mblum.
