### ISSUE TITLE
Search is spamming User bean requests when performing a search 

### ISSUE THREAD

**Issue by mikeblum** [tsgrp/HPI#1206]
![selection_143](https://cloud.githubusercontent.com/assets/3905463/19284604/3dc7cdb2-8fbc-11e6-9170-f5fda8acf1c9.png)

**Comment by gsteimer** [comment]
Any idea on why this is happening or where the requests are originating from?  You marked this as an Alfresco item.  Is it not happening on Dctm/Hbase?

**Comment by dgrumieaux** [comment]
Our client environment saw this when configured to have a user display name filter in the OTC

**Comment by mikeblum** [comment]
I can't seem to replicate this on edge1 with my user but this might have to do with the cocktail of saved searches?

**Comment by dgrumieaux** [comment]
Our client environment is on Alfresco. Wouldn't present on edge1 most likely

**Comment by gsteimer** [comment]
If it is a problem with the user display name filter, then we wouldn't see it in Documentum environments simply because we don't need to configure that filter for Dctm back ends.  I'm guessing it would be an issue for HBase though.

**Comment by mikeblum** [comment]
Issue is here:

```
OC._formatSingleValue = function(propValue, attrConfig, options, jqXhrs, properties)
	{
		if(attrConfig.get("filter") === "date"){
			jqXhrs.push(app.context.dateService.getFormattedDate(propValue).done(function(formattedDate){
				properties[attrConfig.get("ocName")] = formattedDate;
			}));
		} else if(attrConfig.get("filter") === "datetime"){
			jqXhrs.push(app.context.dateService.getFormattedDatetime(propValue).done(function(formattedDatetime){
				properties[attrConfig.get("ocName")] = formattedDatetime;
			}));
		} else if (attrConfig.get("filter") === "userDisplayName") {
			//the userDisplayName filter is intended for items that come back as a username;
			//we'll want to take the loginName and return the displayName
			var loginName = propValue;
			var xhr = app.context.filterService.getUserDisplayName(loginName, function(displayUsername){
			     properties[attrConfig.get("ocName")] = displayUsername;
			 });
			 jqXhrs.push(xhr);
		}
		else{
			return propValue; // nothin to format!
		}
	};
```

**Comment by dgrumieaux** [comment]
We could use something like this to handle the situation... http://caolan.github.io/async/docs.html#memoize

**Comment by mikeblum** [comment]
update on this - I've commented out the offending code in oc.js and forced a linting issue so our client could move on: 

Running "jshint:all" (jshint) task

app/modules/common/oc.js
  line 41  col 68  Empty block.

✖ 1 problem

by running this command:

    grunt clean build:debug jshint:all --project=hpi-demo-dctm

**Comment by mikeblum** [comment]
I think there could be a more elegant solution  on the backend - rather than trying to stash the request on  the frontend.

**Comment by rosenoam** [comment]
Fixed with revision #17065

**Comment by b-k-white** [comment]
This issue was closed but it didn't fix the problem, it just uncommented the code the mike commented out.

**Comment by b-k-white** [comment]
Nevermind, it is cacheing in context.js
