### ISSUE TITLE
Query Restrictions in Admin - Creating invalid URLs

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1361]
When you're in search config, the URL route looks like this:

`/hpi/admin/SearchConfig/${tracId}`

However, when you click on a group in the Query Restriction section, the URL changes to something like:

**Click group to expand**:
![image](https://cloud.githubusercontent.com/assets/1377228/24962681/3c224196-1f62-11e7-87c7-117b54c43760.png)

**Route changes to**:
![image](https://cloud.githubusercontent.com/assets/1377228/24962701/492ceef4-1f62-11e7-8c30-a2819f032c03.png)

Which obviously won't work.  There are two options to fix this:

1. Correctly setup the route so that if the page is refreshed, the user is taken to the Query Restriction section of search config with the correct group expanded
1. Remove the code that changes the URL at all

**Comment by renesaladrigas** [comment]
I was looking into this a few days ago and it seems like the URL is changed because the tags that control the group and object type dropdown containers have an `href` value attached to them that update the URL when clicked. It seemed to me that removing this through the dev tools doesn't seem to affect functionality. So #2 above should be pretty simple if we decide to go that route, we would just need to change some HTML.

**Comment by gsteimer** [comment]
@renesaladrigas I'm fine with that approach unless option 1 is easy, which I'm guessing it's not.

**Comment by grahamsinger** [comment]
Fixed with rev17836.

**Comment by gsteimer** [comment]
@grahamsinger - I just tried this again on edge2 and it's still happening.  Can you verify that your fix made it's way out there?

**Comment by grahamsinger** [comment]
@gsteimer my bad, fix was still in client UAT branch, merged, tested, and commit with revision 17900.

**Comment by gsteimer** [comment]
Awesome, thanks!
