### ISSUE TITLE
Tour Issues - Not running and breaks after stage actions

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1403]
There are a number of issues with the Tour functionality:

- [ ] Tour no longer re-triggers after configuring in user preferences.  See below.
- [ ] When the stage tour runs properly and finishes in the stage, if you execute any action, the tour tries to run again, but in the top left corner of the screen

For the first one, you can tell HPI to give you a tour in user preferences here:

![image](https://cloud.githubusercontent.com/assets/1377228/26499865/a58e8036-41f9-11e7-8f9e-429724add5b6.png)

However, even with those values set to "on", the tour does not display.

For the second issue, I can't actually get a screencam of it since the tour isn't running!  I've seen this multiple times though when the tour was working.  If you can't reproduce once the tour runs, let me know and I'll stop by.

**Comment by gpolonus** [comment]
Fixed with commit #1403

**Comment by gsteimer** [comment]
@gpolonus - I tried this out on edge... the search tour seems to be working fine, but the stage tour still isn't loading.

**Comment by gsteimer** [comment]
Seems like the problem is that this isn't working for case folders.  

Also - after running a tour, I tried viewing document versions.  The tour isn't running anymore, but something definitely is still happening - see the highlight:

![image](https://user-images.githubusercontent.com/1377228/26850268-830c3f90-4acc-11e7-9100-7dafebb44242.png)

**Comment by gpolonus** [comment]
Fixed with commit #18115.
