### ISSUE TITLE
AW Workflow Rules - Not correctly evaluating multiple rules and multiple conditions

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1442]
In my form I have a state list, which uses the OC `stateList` picklist.  In the workflow rules admin, rules should work like this:

* If there's more than one rule, `OR` the rules
* If there's more than one condition within the rule, the conditions are `AND`ed

So here's my rule setup with two conditions:
![image](https://user-images.githubusercontent.com/1377228/28470559-aca1fc68-6dff-11e7-87c9-c0168faa52a9.png)

Essentially - if the state value is not `NM` and it's not  `AZ`, then route to Conan.  However, in the form when I select New Mexico, the form is incorrectly processing the conditions as an `AND`:

![image](https://user-images.githubusercontent.com/1377228/28470606-d4885ab0-6dff-11e7-8440-606b757ad192.png)

**Comment by CRdouglas** [comment]
Branch Name: Workflow rules bugFixes

This Branch aims to fix a few related AW issues that include this issue and naming on the summary page when multiple rules are engaged.

**Comment by CRdouglas** [comment]
In workflow, when multiple rules are tripped, there should be the Assignee/s that correlate to each rule populated in the summary page. Currently, only the first name gets populated.

![image](https://user-images.githubusercontent.com/11527501/35359414-9fae3cde-011f-11e8-8eda-d56b3ddbf68b.png)

As you can see Alice Beecher and Mike Jackson should be populated in the summary page, due to the rules shown above, but only Alice is appears.

![image](https://user-images.githubusercontent.com/11527501/35359459-d01cb38c-011f-11e8-926c-cc630b8cfa71.png)

**Comment by CRdouglas** [comment]
The issue seems to be a combination of how the rule object is being built and how we're checking for validity (whether or not the rules logic matches the "choice" made in the ui). It seems like most of the issues stem from `workflowdefinitionprovider.js`(`createRules()`) and `workflowrule.js`(`isValid() and validate()`).  Also, was looking into `parseRoles()` in `workflow.js`, as well as `workflowdefinitionbuilder.js` (`evaluateRules() and evaluateRulesCollection()`), however, I don't think the issue is there.

**Comment by mwojno-tsg** [comment]
This issue was resolved with OCMS commit: **25880**. The workflow rule and condition was changed a decent amount to account for various logic that can be done by a user. The `workflow.js` was modified to include some edge cases and evaluate the rule logic to show. The following logic is now supported: 
- regular AND (EX: IL and WI)
- regular OR (EX: IL or WI)
- complex OR (EX: (IL and WI) or MI)
- complex AND (EX: (HI or AL) and TN)

CR: gsinger, dgrumieaux

**Comment by gsteimer** [comment]
After the last commit, I'm seeing some really odd behavior with workflow rules.  Marking this issue high priority since I don't want to update release with these updates in place.  We either need to fix these issues or revert.

In Simple CR, we have these rules set up:

![image](https://user-images.githubusercontent.com/1377228/93262744-5c93b700-f76a-11ea-8526-012f5939e84a.png)

However, if I choose either High or Medium, the role owner is selected (Alice Beecher).  Also, notice that the reason is blank and instead of showing the user ID in parentheses, it shows the user name:

![image](https://user-images.githubusercontent.com/1377228/93262799-72a17780-f76a-11ea-9071-44c1494135c8.png)

For the user input rule on the CR Approvers page, if I choose one user, it looks fine:

![image](https://user-images.githubusercontent.com/1377228/93262908-9cf33500-f76a-11ea-9b1e-13b704278e32.png)

However, if I choose more than one approver, the approvers trip correctly but the reason is blank:

![image](https://user-images.githubusercontent.com/1377228/93263021-c57b2f00-f76a-11ea-9a08-d247d8304ded.png)

On my test "State Workflow Rules", no matter what state combination I pick, the resolved user is always the role owner.

**Comment by mwojno-tsg** [comment]
The above issue that was introduced by OCMS commit: **25880** should now be fixed at OCMS revision: **25902**. Two additional logic conditions needed to be added that were missed that Simple CR introduces when using that form. Also, extra left padding to the back button was fixed. Unit test added for the CR Approvers scenario. 

CR: aking, gsinger

**Comment by gsteimer** [comment]
With this latest commit, the logic is much better.  However, I think there's still an issue case and look and feel item outstanding.

**Issue Case** - if a single value is tripped as well as a rule with multiple values, the single valued item is not added.  For example:

![image](https://user-images.githubusercontent.com/1377228/93497204-cd0b1700-f8d5-11ea-90bf-0fafd339cc96.png)

If I select _just_ IL:

![image](https://user-images.githubusercontent.com/1377228/93497349-f2982080-f8d5-11ea-9a2d-ba62ec339781.png)

Select IL and IA (note missing tripped IL rule)

![image](https://user-images.githubusercontent.com/1377228/93497431-08a5e100-f8d6-11ea-99dc-659e2ca8214e.png)

Select IL and CA - Missing both tripped rules

![image](https://user-images.githubusercontent.com/1377228/93497510-1bb8b100-f8d6-11ea-970e-a97826ebf51b.png)

**Look and Feel Enhancement** - it seems that the "reason" box is trying to list out the rules selected for each tripped item, but it doesn't look correct in this scenario:

![image](https://user-images.githubusercontent.com/1377228/93497682-515d9a00-f8d6-11ea-9132-8ecfdbe453a5.png)

In the above case, Pam and Mike were selected because I picked IA - it has nothing to do with the other values.  Instead of trying to nail down each rule, let's just reword the reason box to list out the values that the user selected for the target question and leave it at that.

**Comment by mwojno-tsg** [comment]
Note for Matt - pull down up to date `TS WF User Rules` before testing and completing this last edge case

**Comment by mwojno-tsg** [comment]
This commit was closed with OCMS revision: **26029**. The reason phrases are cleaned up for the 'not equal' and 'equal' cases only to be a little more clear to the user what is being tripped. With displaying question and a list of values selected by the user. Also, there is a logic update to remove the restriction to ONLY show a single selected value. For example, if IL and WI are selected the following rules should be tripped: IL (single user rule) & IL and WI. 

Spec files also updated. workflowruleevaluatorSpec.js is deleted from /tests/app/modules/wizard/ because that was a duplicated file & in wrong place. Combined both workflowruleevaluatorSpec.js files.

CR: aking, gsinger
