### ISSUE TITLE
Non-Quality Chain Versionable Document Cannot be versioned past 1.0

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/HPI#1488]
Assuming #1486 is fixed, if you create a non-quality chain versionable document (ex: `tsg:controlledDocument`) and version it to 1.0, Approved OC fails creating a 1.1 draft version.  The error is:

```
2017-09-27 10:52:53,352	http-apr-8080-exec-8	ERROR	CommonWizardLifecycleBehaviours	Failed running doWork!
org.alfresco.service.cmr.coci.CheckOutCheckInServiceException: 08270040 A working copy cannot be checked out.
	at org.alfresco.repo.coci.CheckOutCheckInServiceImpl.checkout_aroundBody2(CheckOutCheckInServiceImpl.java:399) ~[alfresco-repository-5.1.2.jar:5.1.2]
...
2017-09-27 10:52:53,406	http-apr-8080-exec-8	ERROR	EmbeddedAlfrescoAdvice	Unhandled exception around OC method class: interface com.tsgrp.opencontent.core.content.IContent| name: checkout
org.alfresco.error.AlfrescoRuntimeException: 08270041 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.node.NodeServicePolicies$OnAddAspectPolicy.onAddAspect(org.alfresco.service.cmr.repository.NodeRef,org.alfresco.service.namespace.QName) in transaction 4f83b4b5-d95e-403d-bed4-99f68945f933
...
Caused by: org.alfresco.service.cmr.coci.CheckOutCheckInServiceException: 08270040 A working copy cannot be checked out.
	at org.alfresco.repo.coci.CheckOutCheckInServiceImpl.checkout_aroundBody2(CheckOutCheckInServiceImpl.java:399) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.alfresco.repo.coci.CheckOutCheckInServiceImpl$AjcClosure3.run(CheckOutCheckInServiceImpl.java:1) ~[alfresco-repository-5.1.2.jar:5.1.2]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.2.jar:?]
...
	at com.tsgrp.alfresco.wizard.behaviour.CommonWizardLifecycleBehaviours$1.doWork(CommonWizardLifecycleBehaviours.java:52) ~[bin/:2.6]
	at com.tsgrp.alfresco.wizard.behaviour.CommonWizardLifecycleBehaviours$1.doWork(CommonWizardLifecycleBehaviours.java:1) ~[bin/:2.6]
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555) ~[alfresco-data-model-5.1.2.jar:5.1.2]
	at com.tsgrp.alfresco.wizard.behaviour.CommonWizardLifecycleBehaviours.majorVersionDocumentAndSetApprovalDateAttribute(CommonWizardLifecycleBehaviours.java:30) ~[bin/:2.6]
	at com.tsgrp.alfresco.wizard.behaviour.ControlledDocLifecycleBehaviours.onAddAspect(ControlledDocLifecycleBehaviours.java:79) ~[bin/:2.6]
```

**Comment by gsteimer** [comment]
@ZachGerth has a fix that will go in with #1486

**Comment by ZachGerth** [comment]
Resolved with OC Commit 17416.

**Comment by gsteimer** [comment]
@ZachGerth - seems like this is still an issue on edge2, although I saw this work on my local when I shimmed in your pre-commit changes.  Here's the error on edge2:

```
2017-10-02 14:49:21,516 DEBUG [com.tsgrp.alfresco.chained.versionable.VersionChainPolicy] In VersionChainPolicy#onUpdateProperties with workspace://SpacesStore/eafd366a-2528-4834-9768-dd864afbf374
2017-10-02 14:49:21,516 DEBUG [com.tsgrp.alfresco.chained.versionable.VersionChainPolicy] In VersionChainPolicy#beforeCheckIn for node workspace://SpacesStore/eafd366a-2528-4834-9768-dd864afbf374
2017-10-02 14:49:21,516 DEBUG [com.tsgrp.alfresco.chained.versionable.VersionChainPolicy] Confirmed that the node exists
2017-10-02 14:49:21,516 DEBUG [com.tsgrp.alfresco.chained.versionable.VersionChainPolicy] NodeRef is currently checked out
2017-10-02 14:49:21,516 DEBUG [com.tsgrp.alfresco.chained.versionable.VersionChainPolicy] In VersionChainPolicy#createVersionCopy for workspace://SpacesStore/29695104-7841-40cf-a088-d26655d743e4
2017-10-02 14:49:21,781 ERROR [com.tsgrp.alfresco.chained.versionable.VersionChainPolicy] Failed running doWork!
org.alfresco.service.namespace.InvalidQNameException: A QName must consist of a local name
	at org.alfresco.service.namespace.QName.createQName(QName.java:94)
	at org.alfresco.service.namespace.QName.createQName(QName.java:131)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.associationShouldBeMoved(VersionChainPolicy.java:408)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.updateSourceTargetAssociations(VersionChainPolicy.java:388)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.createVersionCopy(VersionChainPolicy.java:350)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.access$100(VersionChainPolicy.java:52)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy$1.doWork(VersionChainPolicy.java:205)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy$1.doWork(VersionChainPolicy.java:174)
	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:555)
	at com.tsgrp.alfresco.chained.versionable.VersionChainPolicy.beforeCheckIn(VersionChainPolicy.java:174)

```

**Comment by gsteimer** [comment]
looks like this works now with the latest chained versionable AMP applied
