### ISSUE TITLE
License Manager Admin Page

### ISSUE THREAD

**Issue by LoganLaFollette** [tsgrp/HPI#1881]
The current admin page for OCMS is unable to view/update the OC/OCMS license being used.  Adding this functionality would be helpful for users to update the license without having to go directly to the file system location. 

The page would look something like this: 

![image](https://user-images.githubusercontent.com/20171166/56984988-f5616c80-6b4c-11e9-8449-bfe1891b7dac.png)

The main requirements for the new admin page are: 
- [x] The ability to view information on the current, active license(s).
- [x] An upload page/dialogue to add a new license or replace an existing one.

**Comment by LoganLaFollette** [comment]
Implemented with 
OC Revision: 22261
OCMS Revision: 22892

**Comment by gsteimer** [comment]
@LoganLaFollette - clicking on the license admin page on edge2 immediately throws an error

![image](https://user-images.githubusercontent.com/1377228/57460439-b6ad6f80-723a-11e9-8b1d-8cfcb5e071cb.png)

I see this error in the OC logs, but oddly it happened earlier in the log than when I clicked on the License Manager link:

```
2019-05-09 09:07:40,130	ajp-apr-8009-exec-7	ERROR	RESTService	Failed getting node ref at path: /hpi/default/configs/LicenseManager/default
com.tsgrp.opencontent.core.exception.OCObjectNotFoundException: Failed getting node ref at path: /hpi/default/configs/LicenseManager/default
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.getObjectByPath(AlfrescoEmbContentImpl.java:1655) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
	at com.tsgrp.opencontent.alfresco.content.AlfrescoEmbContentImpl.getObjectByPath(AlfrescoEmbContentImpl.java:1631) ~[oc-hpiDemoAlf.2.alfrescoEmb-3.2.0.jar:3.2.0]
```

First thing to check is to make sure that the code is null safe when looking for the LicenseManager config.

Actually - why do we even need this config?  Doesn't the page just read what's sent from OC?

**Comment by LoganLaFollette** [comment]
fixed with OCMS revision: 22914

**Comment by gsteimer** [comment]
This is still not working on edge2.  Looks to be a 404 with some layout files.  From talking to @LoganLaFollette , it looks like it's a Grunt vs. Tomcat thing.  Tomcat is case sensitive when it comes to route paths, whereas Grunt is not.
