### ISSUE TITLE
Checkin from OneDrive using Microsoft Graph API provides a null pointer due to filename encoding

### ISSUE THREAD

**Issue by mwojno-tsg** [tsgrp/HPI#2285]
## Overview
- Currently, a document can be successfully checked out to OneDrive. However, when checking back in a 404 is encountered and document cannot be checked back in. It results in a null pointer issue because the file cannot be found even though it exists. 

- **This only happens on certain documents with how they are named**

## Error Message

```
java.lang.NullPointerException: null
	at com.tsgrp.opencontent.core.action.executer.CheckinFromCloudServiceActionExecuter.checkinFromMicrosoftOnline(CheckinFromCloudServiceActionExecuter.java:260) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.executer.CheckinFromCloudServiceActionExecuter.executeImpl(CheckinFromCloudServiceActionExecuter.java:135) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
```

## Insights
- I believe there is something going on with how the checkout and checkin are handling encoding and trying to find the file within OneDrive. Checkout successfully puts the file their, but checkin cannot seem to find the file to bring it back into our application. 

## Issue Checklist
- [x] Resolve above null pointer / encoding issue
- [x] Add better error handling to provide better insight in the future

**Comment by mwojno-tsg** [comment]
This issue was resolved at OC revision: **26171**. The java URL encoder was providing issue when the document was checked out to OneDrive because it was wrongly encoded. Then, MS OneDrive would correctly encode it changing the file name. This lead to the 404 or null pointer b/c checkin couldn't find the filename. Replace all was used instead to remove special characters and replace with underscore. Better error messages and error handling was added. 

CR: aking, nwoodbine

**Comment by gsteimer** [comment]
@mwojno-tsg - not sure why, but it seems like this NPE is still happening on edge1.  I tried with a doc named `TSG-###`

```
java.lang.NullPointerException: null
	at com.tsgrp.opencontent.core.action.executer.CheckinFromCloudServiceActionExecuter.checkinFromMicrosoftOnline(CheckinFromCloudServiceActionExecuter.java:254) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.executer.CheckinFromCloudServiceActionExecuter.executeImpl(CheckinFromCloudServiceActionExecuter.java:129) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.executeImpl(AbstractActionExecuter.java:239) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.execute(AbstractActionExecuter.java:226) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.executer.AbstractActionExecuter.evaluateAndExecute(AbstractActionExecuter.java:156) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.service.CoreActionService.execute(CoreActionService.java:475) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
	at com.tsgrp.opencontent.core.action.service.RESTAction.executeActionPost(RESTAction.java:226) ~[oc-hpiDemoDctm.1.core-3.4.0.jar:3.4.0]
```

**Comment by gsteimer** [comment]
This was actually a config issue.  The config was set to use an `Organization` onedrive, when in our case it should be `Personal`, which uses the `live.com` version of OneDrive.

![image](https://user-images.githubusercontent.com/1377228/94837909-707e2080-03da-11eb-8ee1-47822b5eefda.png)
