### ISSUE TITLE
Create Wizard Form action - forms are not ordered

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#585]
See the screenshot below.  When clicking to view all forms in the dropdown, the forms are not returned in Alphabetical order.

We should fix this on the OC side to order the query vs. ordering the results on the back end.  Also - this screenshot was from Documentum, but we should test Alfresco too.

![image](https://cloud.githubusercontent.com/assets/1377228/6376506/dd347f74-bce3-11e4-83ef-fb737576f22c.png)

**Comment by tconnellytsg** [comment]
Fixed in OC revision #10962

**Comment by gsteimer** [comment]
@tconnellytsg - this seems to be fixed for Documentum on edge1, but is still wrong on Alfresco:

![image](https://cloud.githubusercontent.com/assets/1377228/6394310/31df21e8-bd96-11e4-9de5-ba196af11dc6.png)

**Comment by gsteimer** [comment]
According to @benallenallen - this is because the old Enhanced Query code doesn't support ordering in Alfresco.

**Comment by aviking** [comment]
Have the alfresco sort fixed locally, waiting for a Code Review.

**Comment by aviking** [comment]
Fixed with HPI Commit: 12194
Code Review: Dan G.
