### ISSUE TITLE
Send Email - TO field disabled if address book doesn't exist

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/hpi#658]
This is related to the changes from #497, but I didn't want to further clutter that issue.

After the KO removal from the email action, it looks like the TO typeahead only populates if the addressbook already exists.  For example on edge2:

**Email from folder 777777 - 2014 (already has an addressbook)**
![image](https://cloud.githubusercontent.com/assets/1377228/7319635/82f029fe-ea5c-11e4-9598-395e5a057ac9.png)

**Email from folder 123123 (no addressbook yet**
To field is always disabled and spinner never disappears
![image](https://cloud.githubusercontent.com/assets/1377228/7319652/9afa3e4a-ea5c-11e4-94cd-7e0689a8d794.png)

@dhartman25 - I'm assuming this is an easy one to fix?

**Comment by grahamsinger** [comment]
Fixed with 12135.

Removed the 'disable()' function in typeahead.js that kept the input disabled when there was nothing returned by the query.

Also, cleaned up some dead code in send email.

CR: M. Blum

**Comment by gsteimer** [comment]
Looks like this is still not working on both edge1 and edge2.  The spinner is no longer displaying, but the TO field is still disabled:

![image](https://cloud.githubusercontent.com/assets/1377228/7394747/2c556818-ee5b-11e4-93aa-647807f4618b.png)

**Comment by dhartman25** [comment]
I talked to @mikeblum about this - he should have a good idea of the scenarios that need to be tested in both HPI and Wizard.

**Comment by grahamsinger** [comment]
I've fixed this locally with unit tests.  Testing with simple CR and reassign workflow task before committing.

**Comment by gsteimer** [comment]
@grahamsinger - just making sure - did you test that the TO field is properly enabled in the Send Email action for a folder that doesn't yet have an address book?

**Comment by grahamsinger** [comment]
Yes, both cases in send email (yes/no address book) are back working.

**Comment by grahamsinger** [comment]
Reworked with revision #12155.

Created an override in the type ahead config for send email.  Type ahead still seems to be functioning properly in wizard, too.

CR: MB

**Comment by gsteimer** [comment]
This *still* does not work on edge:

![image](https://cloud.githubusercontent.com/assets/1377228/7430781/1fd4ce7a-efdd-11e4-8f56-11598254fb01.png)

@grahamsinger @mikeblum

**Comment by grahamsinger** [comment]
Forgot to change the false flags to true when we changed the wording of the override var.

Fixed with revision #12160.
