### ISSUE TITLE
Create Folder - Check for existing folder

### ISSUE THREAD

**Issue by b-k-white** [tsgrp/HPI#798]
When creating a folder, check to see if the objectName of the folder being created already exists, and if so, display a link to that folder

**Comment by b-k-white** [comment]
HPI - 12951
CR - Don
![folderexists](https://cloud.githubusercontent.com/assets/8796489/9582834/5f374502-4fcd-11e5-8657-69952a04fb80.png)


Finished, see screen below

**Comment by gsteimer** [comment]
The current implementation has a few issues:

1. The query does not specify a type, which fails in Documentum
1.  It searches across the whole repository, rather than within the parent folder.  The search should be targeted to children of the parent folder.  The parent folder is:
  - Action in stage - the stage folder
  - Action in HPI header - the configured path for the target type

@b-k-white @dhartman25

**Comment by gsteimer** [comment]
Marking this as an issue since it's spamming error messages to the log in Documentum environments

**Comment by JasonKienzle** [comment]
HPI - 13596
CR - Zaq, Mike

Fixed the initial enhancement to support Alfresco AND DCTM, scoped to just the parent folder of the action

**Comment by JasonKienzle** [comment]
Added a fix and case-insensitive name checking with rev. 13603

**Comment by renesaladrigas** [comment]
Seems like this issue is back. Tested for DCTM environment, not sure if other implementations are seeing the same problems too.
![createnewfolderspamslogs](https://cloud.githubusercontent.com/assets/14186921/23485913/3ed96d4a-fea3-11e6-9a84-93737d656677.gif)

**Comment by gsteimer** [comment]
The error you're seeing is just the result of HPI trying to search for an object that doesn't yet exist.  This is good in your case because you want to create it.  The error is thrown because that method in OC doesn't know whether or not the Object Not Found condition is an error or not.  Most of the time, we do want that error to appear in the logs.  This is one of the cases where the error is an expected (and good) outcome.

If your client is concerned about the stack trace in the log, one possible enhancement would be to have some sort of `quietMode` param (default to `false`).  If it's true, then still throw the `OCObjectNotFoundException`, but don't log it.

Also, I did notice that the Create Folder action was failing on edge1 with a different error:

![image](https://cloud.githubusercontent.com/assets/1377228/23509382/30c4a27e-ff1b-11e6-938f-73252cc2eaeb.png)

This is just a configuration error.  In the admin, it was set to put Policy folders in `/InsuranceDemo/Policy`, but the actual folder is `Policies`.  It's now fixed.
